package com.codeforge.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Task patch entity for code changes generated by AI tasks
 */
@Entity
@Table(name = "task_patches", indexes = {
    @Index(columnList = "task_id")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(exclude = {"task"})
@ToString(exclude = {"task"})
public class TaskPatch {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id", nullable = false)
    private AITask task;
    
    @Column(length = 500, nullable = false)
    private String filePath;
    
    @Column(columnDefinition = "TEXT", nullable = false)
    private String patchContent; // Unified diff format
    
    @Column(length = 50)
    @Enumerated(EnumType.STRING)
    private PatchStatus status; // PENDING, APPROVED, REJECTED, APPLIED
    
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;
    
    public enum PatchStatus {
        PENDING, APPROVED, REJECTED, APPLIED
    }
}
